# Generated by Django 4.0.2 on 2022-05-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctoption',
            name='id',
        ),
        migrations.RemoveField(
            model_name='correctoption',
            name='option_text',
        ),
        migrations.AlterField(
            model_name='correctoption',
            name='option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.option'),
        ),
    ]
