# Generated by Django 4.0.2 on 2022-05-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_timer_remove_question_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correct',
        ),
        migrations.AddField(
            model_name='question',
            name='selected_option',
            field=models.CharField(default='hello', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=100),
        ),
    ]
